### ISSUE TITLE
[Bug] [iOS] TouchEffect inside Frame swallowing child TouchEffect.

### ISSUE THREAD

**Issue by albilaga** [xamarin/XamarinCommunityToolkit#1519]
### Description
In the iOS, when we use Frame as Container with touch effect, and the child of the container also use Touch effect, touch effect in child not getting triggered. This is only happened on iOS. Android working fine.
### Steps to Reproduce

1.  Open the attachment or this is the code snippet
```
<Frame VerticalOptions="Center" Margin="20,0"
           HorizontalOptions="CenterAndExpand" effects:TouchEffect.Command="{Binding ShowAlertCommand}"
           effects:TouchEffect.CommandParameter="Container"
           effects:TouchEffect.ShouldMakeChildrenInputTransparent="False">
        <Frame HasShadow="False" CornerRadius="10" Padding="10" IsClippedToBounds="True"
               BackgroundColor="Purple">
            <Button Text="Go To Game" Margin="10" VerticalOptions="Center" HorizontalOptions="Center"
                    effects:TouchEffect.Command="{Binding ShowAlertCommand}"
                    effects:TouchEffect.CommandParameter="Game Button" />
        </Frame>
    </Frame>
```
2.  Run in Android and click "Go To Game" button. It will show alert with message "Game Button"
3. Now run in iOS and click "Go To Game" button. It will show alert with message "Container", which means the button TouchEffect getting swallowed by container TouchEffect

### Expected Behavior
When click "Go To Game" button, it should behave like in Android (show alert with message "Game Button")
### Actual Behavior
When click "Go To Game" button, it show alert "Container" which means container TouchEffect getting called.

### Basic Information

- Version with issue: 1.2.0
- Last known good version: -
- IDE: Rider
- Platform Target Frameworks: 
  - iOS:  14.5
  - Android: 11
- Nuget Packages: 
  - Xamarin.Forms: 5.0.0.2083
  - Xamarin.CommunityToolkit: 1.2.0
- Affected Devices: iOS

### Reproduction Link
[App1.zip](https://github.com/xamarin/XamarinCommunityToolkit/files/6841679/App1.zip)

**Comment by AndreiMisiukevich** [comment]
@albilaga can you try to set ShouldMakeChildrenInputTransparent=false on your "parent" view?

**Comment by jfversluis** [comment]
Wait, I updated the title, but just to clarify; is it correctly working on iOS or Android? Your first sentence is a bit confusing :D

**Comment by albilaga** [comment]
@jfversluis  Oops. Sorry. It is not working on iOS. Android is the expected behavior....

**Comment by albilaga** [comment]
@AndreiMisiukevich If I add this `xct:TouchEffect.ShouldMakeChildrenInputTransparent="False"` then the child view will not triggering anything

**Comment by AndreiMisiukevich** [comment]
@albilaga can you please run our sample app and navigate to Effects -> TouchEffect
At the bottom, we have a nested view sample which is working fine. You can play with code there.

if all is working fine for you there, then probably you have to use the latest pre-release version or even the nightly package.

This issue should be resolved

**Comment by AndreiMisiukevich** [comment]
And don't use `effects:TouchEffect.ShouldMakeChildrenInputTransparent="False"` in this case

duplicate: https://github.com/xamarin/XamarinCommunityToolkit/issues/1432

**Comment by AndreiMisiukevich** [comment]
Yes, retested on our sample

`xct:TouchEffect.ShouldMakeChildrenInputTransparent="False"` is needed though (On top view)

**Comment by albilaga** [comment]
@AndreiMisiukevich It is still different behavior between Android and iOS. As example I have content like this
```
 <Frame VerticalOptions="Center" Margin="20,0" Padding="30,0" x:Name="ContainerFrame"
           HorizontalOptions="CenterAndExpand" effects:TouchEffect.Command="{Binding ShowAlertCommand}"
           effects:TouchEffect.CommandParameter="Container"
           effects:TouchEffect.NativeAnimation="True"
           effects:TouchEffect.ShouldMakeChildrenInputTransparent="False">
        <Frame x:Name="RedFrame" HasShadow="False" CornerRadius="10" Padding="10" IsClippedToBounds="True"
               BackgroundColor="Red">
            <Button Text="Second Page" Margin="10" VerticalOptions="Center" HorizontalOptions="Center"
                    effects:TouchEffect.Command="{Binding NavigateToSecondPageCommand}"
                    effects:TouchEffect.NativeAnimationColor="#f5f5f5" BackgroundColor="Green"
                    effects:TouchEffect.NativeAnimation="True" />
        </Frame>
    </Frame>
```
In Android when I click on `RedFrame` it is still showing alert with message `Container`. But in iOS it will not doing anything. It should behave the same like between android and iOS?

**Comment by AndreiMisiukevich** [comment]
@albilaga that's a good example, but unfortunately I don't know how to fix that
Can you try to apply touchEffect to Red Frame as well and see if it's a workaround for iOS
